# -*- coding: utf-8 -*-
"""analisis_cpu_integrales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14SmeLyV5eqg3fTNvTekl9cOkFMDPkFDt
"""

import psutil
import numpy as np
import customtkinter as ctk
from matplotlib.figure import Figure
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from threading import Thread

ctk.set_appearance_mode("dark")
ctk.set_default_color_theme("blue")

tiempos = []
cpu_datos = []

ejecutando = False

ventana = ctk.CTk()
ventana.geometry("1400x800")
ventana.title("IntegralCPU Dashboard")


def iniciar():

    global ejecutando

    ejecutando = True

    tiempos.clear()
    cpu_datos.clear()

    texto.delete("1.0", "end")

    hilo = Thread(target=monitorear)

    hilo.start()


def detener():

    global ejecutando

    ejecutando = False

    analizar()


def monitorear():

    tiempo = 0

    while ejecutando:

        uso = psutil.cpu_percent(interval=1)

        tiempos.append(tiempo)
        cpu_datos.append(uso)

        cpuActual.configure(
            text=f"{uso}%"
        )

        promedio = np.mean(cpu_datos)

        promedioLabel.configure(
            text=f"{promedio:.1f}%"
        )

        maximo = np.max(cpu_datos)

        maximoLabel.configure(
            text=f"{maximo:.1f}%"
        )

        integral = np.trapezoid(cpu_datos, tiempos)

        integralLabel.configure(
            text=f"{integral:.1f}"
        )

        estado = ""

        if uso < 30:

            estado = "BAJO"

        elif uso < 60:

            estado = "MEDIO"

        elif uso < 85:

            estado = "ALTO"

        else:

            estado = "EXTREMO"

        texto.insert(
            "end",
            f"Tiempo {tiempo}s  |  CPU {uso}%  |  Estado: {estado}\n"
        )

        texto.see("end")

        actualizarGrafica()

        tiempo += 1


def actualizarGrafica():

    ax.clear()

    ax.plot(
        tiempos,
        cpu_datos,
        linewidth=3
    )

    ax.set_facecolor("#1a1a1a")

    fig.patch.set_facecolor("#1a1a1a")

    ax.set_title(
        "Uso de CPU en Tiempo Real",
        color="white"
    )

    ax.set_xlabel(
        "Tiempo",
        color="white"
    )

    ax.set_ylabel(
        "CPU %",
        color="white"
    )

    ax.tick_params(colors="white")

    ax.grid(True)

    canvas.draw()


def analizar():

    texto.insert(
        "end",
        "\n===== ANÁLISIS FINAL =====\n"
    )

    for i in range(0, len(cpu_datos), 10):

        segmento = cpu_datos[i:i+10]

        promedio = np.mean(segmento)

        if promedio < 30:

            estado = "BAJO"

        elif promedio < 60:

            estado = "MEDIO"

        elif promedio < 85:

            estado = "ALTO"

        else:

            estado = "EXTREMO"

        texto.insert(
            "end",
            f"Intervalo {i}-{i+10}s -> {estado}\n"
        )


titulo = ctk.CTkLabel(
    ventana,
    text="IntegralCPU Dashboard",
    font=("Arial", 35, "bold")
)

titulo.pack(pady=20)


frameTop = ctk.CTkFrame(
    ventana
)

frameTop.pack(
    fill="x",
    padx=20
)


card1 = ctk.CTkFrame(frameTop)
card1.pack(side="left", expand=True, padx=10, pady=10)

ctk.CTkLabel(
    card1,
    text="CPU Actual",
    font=("Arial", 18)
).pack(pady=10)

cpuActual = ctk.CTkLabel(
    card1,
    text="0%",
    font=("Arial", 35, "bold")
)

cpuActual.pack(pady=10)


card2 = ctk.CTkFrame(frameTop)
card2.pack(side="left", expand=True, padx=10, pady=10)

ctk.CTkLabel(
    card2,
    text="Promedio",
    font=("Arial", 18)
).pack(pady=10)

promedioLabel = ctk.CTkLabel(
    card2,
    text="0%",
    font=("Arial", 35, "bold")
)

promedioLabel.pack(pady=10)


card3 = ctk.CTkFrame(frameTop)
card3.pack(side="left", expand=True, padx=10, pady=10)

ctk.CTkLabel(
    card3,
    text="Máximo",
    font=("Arial", 18)
).pack(pady=10)

maximoLabel = ctk.CTkLabel(
    card3,
    text="0%",
    font=("Arial", 35, "bold")
)

maximoLabel.pack(pady=10)


card4 = ctk.CTkFrame(frameTop)
card4.pack(side="left", expand=True, padx=10, pady=10)

ctk.CTkLabel(
    card4,
    text="Integral",
    font=("Arial", 18)
).pack(pady=10)

integralLabel = ctk.CTkLabel(
    card4,
    text="0",
    font=("Arial", 35, "bold")
)

integralLabel.pack(pady=10)


frameBotones = ctk.CTkFrame(
    ventana
)

frameBotones.pack(
    pady=20
)


botonIniciar = ctk.CTkButton(
    frameBotones,
    text="Iniciar",
    width=200,
    height=50,
    command=iniciar
)

botonIniciar.pack(
    side="left",
    padx=20
)


botonDetener = ctk.CTkButton(
    frameBotones,
    text="Detener",
    width=200,
    height=50,
    fg_color="red",
    hover_color="#aa0000",
    command=detener
)

botonDetener.pack(
    side="left",
    padx=20
)


frameCentro = ctk.CTkFrame(
    ventana
)

frameCentro.pack(
    fill="both",
    expand=True,
    padx=20,
    pady=20
)


fig = Figure(
    figsize=(10,4),
    dpi=100
)

ax = fig.add_subplot(111)

canvas = FigureCanvasTkAgg(
    fig,
    master=frameCentro
)

canvas.get_tk_widget().pack(
    fill="both",
    expand=True,
    pady=10
)


texto = ctk.CTkTextbox(
    frameCentro,
    height=180,
    font=("Consolas", 14)
)

texto.pack(
    fill="x",
    pady=10
)


ventana.mainloop()